"""initial schema

Revision ID: b7aa62a2c65e
Revises: 
Create Date: 2026-03-22 18:13:02.398320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7aa62a2c65e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # A fresh database does not inherit extensions from the image's template.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shark_species',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('common_name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=100), nullable=False),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('danger_rating', sa.String(length=20), nullable=True),
    sa.Column('max_size_meters', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scientific_name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    comment='Users and contributors'
    )
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(length=20), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=True),
    sa.Column('incident_time', sa.Time(), nullable=True),
    sa.Column('date_precision', sa.String(length=10), nullable=False),
    sa.Column('location_description', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('county_region', sa.String(length=100), nullable=True),
    sa.Column('body_of_water', sa.String(length=200), nullable=True),
    sa.Column('coordinates', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('location_precision', sa.String(length=20), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('classification_subtype', sa.String(length=20), nullable=True),
    sa.Column('provocation_subtype', sa.String(length=20), nullable=True),
    sa.Column('shark_species_confirmed', sa.String(length=100), nullable=True),
    sa.Column('shark_species_suspected', sa.String(length=100), nullable=True),
    sa.Column('shark_size_estimate', sa.String(length=100), nullable=True),
    sa.Column('species_identification_method', sa.String(length=50), nullable=True),
    sa.Column('victim_activity', sa.String(length=100), nullable=True),
    sa.Column('victim_injury_severity', sa.String(length=20), nullable=True),
    sa.Column('victim_injury_description', sa.Text(), nullable=True),
    sa.Column('victim_age', sa.Integer(), nullable=True),
    sa.Column('victim_sex', sa.String(length=10), nullable=True),
    sa.Column('victim_name', sa.String(length=200), nullable=True),
    sa.Column('fatal', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("classification IN ('unprovoked', 'provoked', 'boat_bite', 'scavenge', 'aquaria', 'doubtful', 'no_assignment', 'not_confirmed')", name='valid_classification'),
    sa.CheckConstraint("verification_status IN ('pending', 'verified', 'rejected', 'needs_review')", name='valid_verification'),
    sa.CheckConstraint("victim_injury_severity IN ('fatal', 'severe', 'moderate', 'minor', 'no_injury') OR victim_injury_severity IS NULL", name='valid_severity'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_table('incident_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_title', sa.String(length=500), nullable=True),
    sa.Column('source_publisher', sa.String(length=200), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('source_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_sources')
    op.drop_table('incident_audit_log')
    op.drop_table('incidents')
    op.drop_table('users')
    op.drop_table('shark_species')
    # ### end Alembic commands ###
